### ISSUE TITLE
When uploading .doc files, preview fails

### ISSUE THREAD

**Issue by sashman** [pdubois/docker-alfresco#9]
Hey,

When I upload a .doc or .docx file, the thumbnail and preview for the file fail. I'm assuming there's a problem with libreoffice conversion. The thumbnail defaults to a Word doc icon and the preview frame displays: "This document can't be previewed. Click here to download it."

Full stack trace from stdout:

```
2017-10-28 09:32:06,979  ERROR [repo.action.AsynchronousActionExecutionQueueImpl] [defaultAsyncAction2] Failed to execute asynchronous action: Action[ id=82422227-2b7e-4ea0-95fd-3b0bfbb69aac, node=null ]: 09280058 No thumbnail present in file, unable to generate image/jpeg
 org.alfresco.error.AlfrescoRuntimeException: 09280061 Creation of thumbnail 'doclib' failed
	at org.alfresco.repo.thumbnail.CreateThumbnailActionExecuter.executeImpl(CreateThumbnailActionExecuter.java:213)
	at org.alfresco.repo.action.executer.ActionExecuterAbstractBase.execute(ActionExecuterAbstractBase.java:274)
	at org.alfresco.repo.action.ActionServiceImpl.directActionExecution(ActionServiceImpl.java:846)
	at org.alfresco.repo.action.ActionServiceImpl.executeActionImpl(ActionServiceImpl.java:747)
	at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper$1$1.execute(AsynchronousActionExecutionQueueImpl.java:430)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:333)
	at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper$1.doWork(AsynchronousActionExecutionQueueImpl.java:439)
	at org.alfresco.repo.tenant.TenantUtil.runAsWork(TenantUtil.java:126)
	at org.alfresco.repo.tenant.TenantUtil.runAsTenant(TenantUtil.java:95)
	at org.alfresco.repo.tenant.TenantUtil$1.doWork(TenantUtil.java:69)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555)
	at org.alfresco.repo.tenant.TenantUtil.runAsUserTenant(TenantUtil.java:65)
	at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper.run(AsynchronousActionExecutionQueueImpl.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.alfresco.service.cmr.repository.ContentIOException: 09280060 Content conversion failed: 
   reader: ContentAccessor[ contentUrl=store://2017/10/28/9/32/ee060c8a-50a3-464e-9596-0c814fd6d158.bin, mimetype=application/vnd.openxmlformats-officedocument.wordprocessingml.document, size=27129, encoding=UTF-8, locale=en]
   writer: ContentAccessor[ contentUrl=store://2017/10/28/9/32/adf5ca82-89a0-4eeb-a676-4dd792837ae2.bin, mimetype=image/png, size=0, encoding=UTF-8, locale=en_US]
   options: {use=doclib, contentReaderNodeRef=workspace://SpacesStore/eae81955-ea86-4f2e-8eee-b526e75b636d, contentWriterNodeRef=null, sourceContentProperty=null, imageAutoOrient=true, targetContentProperty=null, commandOptions=, imageResizeOptions=ImageResizeOptions [width=100, height=100, maintainAspectRatio=true, percentResize=false, resizeToThumbnail=false, allowEnlargement=false], includeEmbedded=null}
   limits: {timeoutMs=120000, pageLimit=1}
	at org.alfresco.repo.content.transform.AbstractContentTransformer2.transform(AbstractContentTransformer2.java:350)
	at org.alfresco.repo.content.ContentServiceImpl.transform(ContentServiceImpl.java:613)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.model.ml.MLContentInterceptor.invoke(MLContentInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:166)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy54.transform(Unknown Source)
	at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable$1.doWork(AbstractTransformationRenderingEngine.java:447)
	at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable$1.doWork(AbstractTransformationRenderingEngine.java:1)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555)
	at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable.call(AbstractTransformationRenderingEngine.java:437)
	at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable.call(AbstractTransformationRenderingEngine.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: org.alfresco.service.cmr.repository.ContentIOException: 09280059 Content conversion failed: 
   reader: ContentAccessor[ contentUrl=store://2017/10/28/9/32/ee060c8a-50a3-464e-9596-0c814fd6d158.bin, mimetype=application/vnd.openxmlformats-officedocument.wordprocessingml.document, size=27129, encoding=UTF-8, locale=en]
   writer: ContentAccessor[ contentUrl=store:///opt/alfresco/tomcat/temp/Alfresco/ComplextTransformer_intermediate_docx_4429795930063718248.jpg, mimetype=image/jpeg, size=0, encoding=UTF-8, locale=en_US]
   options: {use=doclib, contentReaderNodeRef=workspace://SpacesStore/eae81955-ea86-4f2e-8eee-b526e75b636d, contentWriterNodeRef=null, sourceContentProperty=null, imageAutoOrient=true, targetContentProperty=null, commandOptions=, imageResizeOptions=ImageResizeOptions [width=100, height=100, maintainAspectRatio=true, percentResize=false, resizeToThumbnail=false, allowEnlargement=false], includeEmbedded=null}
   limits: {timeoutMs=120000, pageLimit=1}
	at org.alfresco.repo.content.transform.AbstractContentTransformer2.transform(AbstractContentTransformer2.java:350)
	at org.alfresco.repo.content.ContentServiceImpl.transform(ContentServiceImpl.java:613)
	at org.alfresco.repo.content.transform.ComplexContentTransformer.transformInternal(ComplexContentTransformer.java:483)
	at org.alfresco.repo.content.transform.AbstractContentTransformer2.transform(AbstractContentTransformer2.java:272)
	... 31 more
Caused by: org.alfresco.repo.content.transform.UnimportantTransformException: 09280058 No thumbnail present in file, unable to generate image/jpeg
	at org.alfresco.repo.content.transform.OOXMLThumbnailContentTransformer.transformInternal(OOXMLThumbnailContentTransformer.java:146)
	at org.alfresco.repo.content.transform.AbstractContentTransformer2.transform(AbstractContentTransformer2.java:272)
	... 34 more
```

**Comment by mykolapolonskyi** [comment]
Does LibreOffice alive on your instance? 
Ifs alive inside the same docker container or externally?  
Did you check your settings of  `{timeoutMs=120000, pageLimit=1}`
p.s.  I think you should extend description - not enough information - e.g. no alfresco.properties snippet, no snippet of `docker-compose.yml` or docker command that u use for up you alfresco.

**Comment by sashman** [comment]
Really sorry, I was looking at the wrong image on docker hub! Closing issue
